# Generated by Django 5.0.3 on 2024-03-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interns_Name', models.CharField(max_length=50)),
                ('Domain', models.CharField(max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Assessed_By', models.CharField(max_length=50)),
                ('Conceptual_Understanding', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Understanding_and_explaining_Code', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Technical_Skills', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Analytical_Skills', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Communication', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('Recommendations', models.TextField()),
                ('Created_by', models.CharField(max_length=50)),
                ('Created_date_and_Time', models.DateTimeField(auto_now_add=True)),
                ('Modified_by', models.CharField(default='Admin', max_length=50)),
                ('Modified_date_and_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
