# Generated by Django 5.0.3 on 2024-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Referred_by', models.CharField(max_length=40)),
                ('DOB', models.DateField()),
                ('Address', models.CharField(max_length=60)),
                ('Mobile_Number', models.CharField(max_length=10)),
                ('Email_ID', models.EmailField(max_length=254, unique=True)),
                ('Qualification', models.CharField(max_length=40)),
                ('Year_of_complementation', models.IntegerField()),
                ('Created_by', models.CharField(max_length=50)),
                ('Created_date_and_Time', models.DateTimeField(auto_now_add=True)),
                ('Modified_by', models.CharField(default='Admin', max_length=50)),
                ('Modified_date_and_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
